server:
  port: ${SERVER_PORT:8084}

spring:
  mvc:
    problemdetails:
      enabled: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: true
  application:
    name: recommendation-service
  datasource:
    url: ${CLICKHOUSE_URL:jdbc:ch:http://recommendation-db:8123/spotty_analytics_db}?compress=0
    username: ${CLICKHOUSE_USER:spotty_clickhouse_user}
    password: ${CLICKHOUSE_PASSWORD:your_secure_clickhouse_password}
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
