apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  labels:
    app: recommendation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
        - name: recommendation-service
          image: recommendation-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
              name: http
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: spotty-config
                  key: RECOMMENDATION_SERVICE_PORT
            - name: CLICKHOUSE_URL
              valueFrom:
                configMapKeyRef:
                  name: spotty-config
                  key: CLICKHOUSE_URL
            - name: CLICKHOUSE_USER
              valueFrom:
                configMapKeyRef:
                  name: spotty-config
                  key: CLICKHOUSE_USER
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spotty-secrets
                  key: CLICKHOUSE_PASSWORD
          resources:
            requests:
              cpu: 250m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 768Mi
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 20

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 15
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            periodSeconds: 10
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  labels:
    app: recommendation-service
spec:
  type: ClusterIP
  selector:
    app: recommendation-service
  ports:
    - port: 8084
      targetPort: http
      name: http